name: Deploy Docsify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (if needed)
        working-directory: ./outliyr-framework
        run: npm install || true

      - name: Run convert.js
        working-directory: ./outliyr-framework
        run: node scripts/convert.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./outliyr-framework/docsify
          force_orphan: true
